# Generated by Django 4.0.5 on 2022-06-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskgroup",
            options={"permissions": (("assign_tasks", "Assign task"),)},
        ),
    ]
